export const airports = [
  {
    id: 1,
    city: "Jakarta",
    code: "CGK",
    name: "Soekarno-Hatta International Airport",
    country: "Indonesia",
  },
  {
    id: 2,
    city: "Surabaya",
    code: "SUB",
    name: "Juanda International Airport",
    country: "Indonesia",
  },
  {
    id: 3,
    city: "Denpasar",
    code: "DPS",
    name: "Ngurah Rai International Airport",
    country: "Indonesia",
  },
  {
    id: 4,
    city: "Melbourne",
    code: "MEL",
    name: "Melbourne Airport",
    country: "Australia",
  },
  {
    id: 5,
    city: "Sydney",
    code: "SYD",
    name: "Sydney Kingsford Smith Airport",
    country: "Australia",
  },
  {
    id: 6,
    city: "Singapore",
    code: "SIN",
    name: "Changi Airport",
    country: "Singapore",
  },
  {
    id: 7,
    city: "Tokyo",
    code: "HND",
    name: "Tokyo Haneda Airport",
    country: "Japan",
  },
  {
    id: 8,
    city: "London",
    code: "LHR",
    name: "Heathrow Airport",
    country: "United Kingdom",
  },
  {
    id: 9,
    city: "New York",
    code: "JFK",
    name: "John F. Kennedy International Airport",
    country: "United States",
  },
  {
    id: 10,
    city: "Dubai",
    code: "DXB",
    name: "Dubai International Airport",
    country: "United Arab Emirates",
  },
  {
    id: 11,
    city: "Medan",
    code: "KNO",
    name: "Kualanamu International Airport",
    country: "Indonesia",
  },
  {
    id: 12,
    city: "Makassar",
    code: "UPG",
    name: "Sultan Hasanuddin International Airport",
    country: "Indonesia",
  },
  {
    id: 13,
    city: "Bandung",
    code: "BDO",
    name: "Husein Sastranegara International Airport",
    country: "Indonesia",
  },
  {
    id: 14,
    city: "Balikpapan",
    code: "BPN",
    name: "Sultan Aji Muhammad Sulaiman Airport",
    country: "Indonesia",
  },
  {
    id: 15,
    city: "Yogyakarta",
    code: "YIA",
    name: "Yogyakarta International Airport",
    country: "Indonesia",
  },
  {
    id: 16,
    city: "Palembang",
    code: "PLM",
    name: "Sultan Mahmud Badaruddin II Airport",
    country: "Indonesia",
  },
  {
    id: 17,
    city: "Bangkok",
    code: "BKK",
    name: "Suvarnabhumi Airport",
    country: "Thailand",
  },
  {
    id: 18,
    city: "Kuala Lumpur",
    code: "KUL",
    name: "Kuala Lumpur International Airport",
    country: "Malaysia",
  },
  {
    id: 19,
    city: "Hong Kong",
    code: "HKG",
    name: "Hong Kong International Airport",
    country: "Hong Kong",
  },
  {
    id: 20,
    city: "Shanghai",
    code: "PVG",
    name: "Shanghai Pudong International Airport",
    country: "China",
  },
  {
    id: 21,
    city: "Paris",
    code: "CDG",
    name: "Charles de Gaulle Airport",
    country: "France",
  },
  {
    id: 22,
    city: "Frankfurt",
    code: "FRA",
    name: "Frankfurt Airport",
    country: "Germany",
  },
  {
    id: 23,
    city: "Amsterdam",
    code: "AMS",
    name: "Amsterdam Schiphol Airport",
    country: "Netherlands",
  },
  {
    id: 24,
    city: "Seoul",
    code: "ICN",
    name: "Incheon International Airport",
    country: "South Korea",
  },
  {
    id: 25,
    city: "Doha",
    code: "DOH",
    name: "Hamad International Airport",
    country: "Qatar",
  },
  {
    id: 26,
    city: "Los Angeles",
    code: "LAX",
    name: "Los Angeles International Airport",
    country: "United States",
  },
  {
    id: 27,
    city: "San Francisco",
    code: "SFO",
    name: "San Francisco International Airport",
    country: "United States",
  },
  {
    id: 28,
    city: "Istanbul",
    code: "IST",
    name: "Istanbul Airport",
    country: "Turkey",
  },
  {
    id: 29,
    city: "Toronto",
    code: "YYZ",
    name: "Toronto Pearson International Airport",
    country: "Canada",
  },
  {
    id: 30,
    city: "Mumbai",
    code: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    country: "India",
  },
  {
    id: 31,
    city: "Jakarta",
    code: "JKTA",
    name: "All Airports in Jakarta",
    country: "Indonesia",
  },
];

console.log(airports);
