export const getSeatsData = () => [
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A2",
    isAvailable: true,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A3",
    isAvailable: false,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A4",
    isAvailable: false,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A5",
    isAvailable: false,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A6",
    isAvailable: true,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A8",
    isAvailable: false,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A9",
    isAvailable: false,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A11",
    isAvailable: true,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "A12",
    isAvailable: false,
  },
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B2",
    isAvailable: true,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B3",
    isAvailable: false,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B4",
    isAvailable: false,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B5",
    isAvailable: false,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B6",
    isAvailable: true,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B8",
    isAvailable: false,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B9",
    isAvailable: false,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B11",
    isAvailable: true,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "B12",
    isAvailable: false,
  },
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C2",
    isAvailable: true,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C3",
    isAvailable: false,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C4",
    isAvailable: true,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C5",
    isAvailable: false,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C6",
    isAvailable: true,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C8",
    isAvailable: false,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C9",
    isAvailable: false,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C11",
    isAvailable: true,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "C12",
    isAvailable: false,
  },
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D2",
    isAvailable: false,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D3",
    isAvailable: true,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D4",
    isAvailable: true,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D5",
    isAvailable: true,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D6",
    isAvailable: true,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D8",
    isAvailable: true,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D9",
    isAvailable: true,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D11",
    isAvailable: false,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "D12",
    isAvailable: true,
  },
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E2",
    isAvailable: false,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E3",
    isAvailable: true,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E4",
    isAvailable: true,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E5",
    isAvailable: true,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E6",
    isAvailable: true,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E8",
    isAvailable: true,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E9",
    isAvailable: true,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E11",
    isAvailable: false,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "E12",
    isAvailable: true,
  },
  {
    seat_id: 1,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F1",
    isAvailable: false,
  },
  {
    seat_id: 2,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F2",
    isAvailable: false,
  },
  {
    seat_id: 3,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F3",
    isAvailable: true,
  },
  {
    seat_id: 4,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F4",
    isAvailable: true,
  },
  {
    seat_id: 5,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F5",
    isAvailable: true,
  },
  {
    seat_id: 6,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F6",
    isAvailable: false,
  },
  {
    seat_id: 7,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F7",
    isAvailable: true,
  },
  {
    seat_id: 8,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F8",
    isAvailable: true,
  },
  {
    seat_id: 9,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F9",
    isAvailable: true,
  },
  {
    seat_id: 10,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F10",
    isAvailable: false,
  },
  {
    seat_id: 11,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F11",
    isAvailable: false,
  },
  {
    seat_id: 12,
    flight_id: 1,
    class: "Economy",
    price: 147,
    seat_number: "F12",
    isAvailable: true,
  },
];
